site:
  title:
  subtitle:
  description:
  author:
  timezone:
  url:
  lang: en
  alternate: testName # 站点大标题

footer:
  # Specify the date when the site was set up. If not defined, current year will be used.
  since: 2022
  icon:
    name: sakura rotate
    # Change the color of icon, using Hex Code.
    color: '#ffc0cb'
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true
  powered: true
  icp: # ICP备案
    enable: false
    # 请在登录后从 https://beian.mps.gov.cn/web/business/businessHome/website 下载对应图标
    icon: '' # 网安备案图片
    icpnumber: xxx # ICP备案号
    beian: xxx # 网安备案号
    recordcode: xxx # 网安备案链接中的recordcode参数

loader:
  start: true # 进入页面时显示加载动画
  switch: false # 切换页面时显示加载动画

algolia:
  enable: false
  indexName:
  appId:
  apiKey:

experiments:
  mobileWidth: 820px

font:
  enable: true
  # 从google字体库加载,如果自定义@font-face请关闭
  loadFromGoogle: true
  # 字体选项:
  # `external`:从google字体库加载字体.
  # `family: 字体家族名,无需引号
  # `size: x.x`. 以`em`为单位. 默认: 1 (16px)

  # 适用于所有在body标签内的文字.
  global:
    external: true
    family: Mulish
    size:

  # 大标题字体.
  logo:
    external: true
    family: Fredericka the Great
    size: 3.5

  # 页面标题字体.
  title:
    external: true
    family: Noto Serif JP
    size: 2.5

  # 标题字体.
  headings:
    external: true
    family: Noto Serif SC
    size:

  # 文章字体.
  posts:
    external: false
    family:

  # 代码块的字体
  codes:
    external: true
    family: Inconsolata

# //at.alicdn.com/t/c/font_4415496_59g1326wajd.css => 4415496_59g1326wajd
# 自定义iconfont图标参见文档教程
iconfont: "4415496_59g1326wajd"

visitor:
  clarity: false
  baiduAnalytics: false
  googleAnalytics: false

# 显示的动画(烟花)
# 参阅 https://github.com/D-Sketon/mouse-firework
fireworks:
  enable: true
  options: 
    excludeElements: ["a"]
    particles:
      - shape: circle
        move: ["emit"]
        easing: easeOutExpo
        colors: 
          - "rgba(255,182,185,.9)"
          - "rgba(250,227,217,.9)"
          - "rgba(187,222,214,.9)"
          - "rgba(138,198,209,.9)"
        number: 30
        duration: [1200, 1800]
        shapeOptions:
          radius: [16, 32]
      - shape: circle
        move: ["diffuse"]
        easing: easeOutExpo
        colors: ["#fff"]
        number: 1
        duration: [1200, 1800]
        shapeOptions:
          radius: 20
          alpha: 0.5
          lineWidth: 6